### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'imscISD')

### ISSUE THREAD

**Issue by abhidev54** [sandflow/imscJS#254]
Hi Team,

I am using one library which internally uses imscjs library for CC handling.
I am getting below error, do you know how to resolve or ignore this error ?

Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'imscISD')
    at 2206 (isd.js:809:42)
    at t (bootstrap:19:32)
    at 89953 (main.js:27:23)
    at t (bootstrap:19:32)
    at 69785 (hotkeys.esm.js:619:1)
    at t (bootstrap:19:32)
    at sharing:42:435
    at t.m.<computed> (consumes:196:23)
    at t (bootstrap:19:32)
    at 46463 (8052.ff23f179.chunk.js:1:2899)

isd.js is creating issue, below is problematic code snippet, I am not even calling this file but somehow it get triggered, since imsc.ISD is not defined globally, it is throwing error
(typeof exports === 'undefined' ? **this.imscISD** = {} : exports,
    typeof imscNames === 'undefined' ? require("./names") : imscNames,
    typeof imscStyles === 'undefined' ? require("./styles") : imscStyles,
    typeof imscUtils === 'undefined' ? require("./utils") : imscUtils
    );

Regards.
Abhishek

**Comment by palemieux** [comment]
Can you provide more details on your runtime and development environment?

**Comment by abhidev54** [comment]
Hi @palemieux ,

Actually I am deploying on AWS using Jenkins and building using webpack.

**Comment by palemieux** [comment]
imscJS is built using browserify, so there might be an incompatibility somewhere. Are you packaging `imsc.js` using webpack or building imsc.js using webpack?

**Comment by palemieux** [comment]
@abhidev54 Does the proposed move to [ES6](https://github.com/sandflow/imscJS/pull/255) resolve your issue?
